### PR TITLE
[Mod Support] Legacy4J

### PR DESCRIPTION
**Pull request by aricloverEXTRA**
Hello, I saw this and was interested into making a High Contrast version of the Mod called [Legacy4J](https://modrinth.com/mod/legacy4j)!

Heres a comparison with the resource pack **off** and with the resource pack **on** below.

**OFF**
IMG_2127

**ON**
ON

If any of the textures I added are incorrect or not necessary, you can change them if you’d like! 👍

### CODE REVIEW

**Comment by RhythmicSys** [comment]
ooh this looks awesome! Thanks for this!

**Comment by aricloverEXTRA** [comment]
No problem! I tried to make it look similar to the other textures in the resource pack, glad it looks good!

**Comment by aricloverEXTRA** [comment]
Fun Fact: This was the beta version of the Legacy4J High Contrast assets but changed it before this pull request happened because it didn’t look right.

**Comment by RhythmicSys** [comment]
Finally got the release out, https://modrinth.com/resourcepack/high-contrast-extended/version/1.11

**Comment by aricloverEXTRA** [comment]
Should I make a change to invert the arrow sprites in this?
Here’s the image with the change below.
IMG_2158

**Comment by RhythmicSys** [comment]
I personally find the first one easier to see, but I also am not someone who uses that particular mod, so I don't know how it fits into the overall structure of the mod

**Pull request merged**
